services:
  app-frontend-1:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${TAG}
    #container_name: mesh-business-frontend-prod
    restart: unless-stopped
    ports:
      - "3001:3000" # Maps host port 3000 to container port 3000
    environment:
      - SERVER_PORT=3000
    env_file:
      - .env.deployment-frontend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
     
    networks:
      - mesh-network

  app-frontend-2:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${TAG}
    #container_name: mesh-business-frontend-prod
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - SERVER_PORT=3000 # Maps host port 3000 to container port 3000
    env_file:
      - .env.deployment-frontend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    
    networks:
      - mesh-network

  app-frontend-3:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${TAG}
    #container_name: mesh-business-frontend-prod
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - SERVER_PORT=3000 # Maps host port 3000 to container port 3000
    env_file:
      - .env.deployment-frontend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

    networks:
      - mesh-network

  # Load Balancer Service/reverse proxy
  load-balancer-frontend:
    image: nginx:alpine
    ports:
      - "3000:80" # Expose the load balancer on the main port (3000)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom config
    depends_on:
      - app-frontend-1
      - app-frontend-2
      - app-frontend-3
    networks:
      - mesh-network

volumes:
  postgres-data:
networks:
  mesh-network:
    driver: bridge