services:
  mesh-business-frontend:
    image: 692327579998.dkr.ecr.us-east-1.amazonaws.com/mesh-business-frontend:${TAG}
    container_name: mesh-business-frontend
    restart: unless-stopped

    ports:
      - "3000:3000"
    env_file:
      - .env.staging
    networks:
      - mesh-business-network
  
networks:
  mesh-business-network:
    driver: bridge