events {
    worker_connections 1024;
}

http {
    upstream backend {
        # Define health check parameters
        # If a server fails 3 consecutive requests, it is marked as unavailable for 30 seconds.
        server app-frontend-1:3000 max_fails=3 fail_timeout=30s;
        server app-frontend-2:3000 max_fails=3 fail_timeout=30s;
        server app-frontend-3:3000 max_fails=3 fail_timeout=30s;

    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Optional: Set a timeout for connecting to the backend
            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;
        }
    }
}